name: Workflow acionado por push e agendamento

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Workflow executado com sucesso!"